server:
  port: 10000
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true #使用小写service-id
      routes:
        - id: starrism-mall-admin
          uri: lb://starrism-mall-admin
          predicates:
            - Path=/admin/**
        - id: starrism-mall-auth
          uri: lb://starrism-mall-auth
          predicates:
            - Path=/auth/**
  redis:
    database: 0
    host: 127.0.0.1
    #    host: 1.15.57.220
    port: 6379
    #    password: Redis.166Gcq2431
# Sa-Token 配置
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: Authorization
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 2592000
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  activity-timeout: -1
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: false
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: true
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: false
  token-prefix: Bearer
  jwt-secret-key: aGVkd2luZ3NlY3JldA==
logging:
  level:
    org.starrism.mall: debug
seata:
  # 是否开启spring-boot自动装配
  enabled: true
  # Seata 应用编号，默认为 ${spring.application.name}
  application-id: ${spring.application.name}
  # Seata 事务组编号，用于 TC 集群名。该配置需要与服务端提到的group相对应，也需要与下面的相对应
  tx-service-group: ${spring.application.name}-group
  # 服务配置项
  service:
    # 虚拟组和分组的映射
    vgroupMapping:
      netty-seata-test-group: default   #该配置需要与服务端提到的group相对应
      default:
        # 仅注册中心为file时使用
        grouplist: 127.0.0.1:15000
  config:
    type: nacos
    nacos:
      server-addr: ${spring.cloud.nacos.config.server-addr}
      namespace: SEATA
      group: SEATA_GROUP
      username: nacos
      password: nacos
      data-id: seata-server.yml
  registry:
    type: nacos
    nacos:
      server-addr: ${spring.cloud.nacos.config.server-addr}
      namespace: SEATA
      group: SEATA_GROUP
      username: nacos
      password: nacos
      cluster: default