server:
  port: 10000
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true #使用小写service-id
      routes:
        - id: starrism-mall-admin
          uri: lb://starrism-mall-admin
          predicates:
            - Path=/admin/**
  redis:
    database: 0
    host: 1.15.57.220
    port: 6379
    password: Redis.166Gcq2431